#!/bin/bash

#Description : Docker installation on Centos 7
#Author :Gerard tchakoute
#Date : 27 Feb 2022

# Clean up the system(It’s OK if yum reports that none of these packages are installed.)

sudo yum remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-engine

#Setup the docker repository

sudo yum install yum-utils -y

sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

#Install, start and enable the docker engine

sudo yum install docker-ce docker-ce-cli containerd.io -y
sudo systemctl start docker
sudo systemctl enable docker

#Check the status of the daemon to make sure it is up and running with

sudo systemctl status docker
docker --version
