#!/bin/bash
#Description : Docker installation on Oracle Linux 7
#Author :Gerard tchakoute
#Date : 16 March 2022


# Clean up the system(It’s OK if yum reports that none of these packages are installed.)

sudo yum remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-engine

#Setup the docker repository

sudo yum install -y yum-utils
sudo yum-config-manager \
    --add-repo \
        https://download.docker.com/linux/centos/docker-ce.repo
	sudo sed -i 's/$releasever/7/g' /etc/yum.repos.d/docker-ce.repo
	mkdir rpms && cd rpms
	wget http://mirror.centos.org/centos/7/extras/x86_64/Packages/slirp4netns-0.4.3-4.el7_8.x86_64.rpm
	wget http://mirror.centos.org/centos/7/extras/x86_64/Packages/fuse3-libs-3.6.1-4.el7.x86_64.rpm
	wget http://mirror.centos.org/centos/7/extras/x86_64/Packages/fuse-overlayfs-0.7.2-6.el7_8.x86_64.rpm
	sudo rpm -Uvh slirp4netns-0.4.3-4.el7_8.x86_64.rpm fuse3-libs-3.6.1-4.el7.x86_64.rpm fuse-overlayfs-0.7.2-6.el7_8.x86_64.rpm

#Install the docker engine and check the version

sudo yum install docker-ce docker-ce-cli containerd.io -y
cd .. && rm -rf rpms
docker --version

#start and enable the docker engine

sudo systemctl start docker
sudo systemctl enable docker

#Check the status of the daemon to make sure it is up and running with

sudo systemctl status docker
